username = input()
password = input()
name, age, bmi = input().split()
bmi = float(bmi)
print("<user>")
print("\t<combo>", username, ":", password, "</combo>", sep="")
print("\t<name>", name, "</name>", sep="")
print("\t<age>", age, "</age>", sep="")
print("\t<bmi>", "{bmi:.3f}".format(bmi=bmi), "</bmi>", sep="")
print("</user>")